import {
  Code,
  HeartPulse,
  GraduationCap,
  TrendingUp,
  Scale,
  Cpu,
  Palette,
  Languages,
  Wheat,
  Brain,
  Building2,
  Megaphone,
  HardHat,
  Zap,
  Briefcase,
  Stethoscope,
  Ruler,
  LineChart,
  type LucideIcon,
} from "lucide-react";
import type { Category } from "@/types/categories";

export const CATEGORIES: Category[] = [
  { id: "it", name: "IT", description: "Программирование, технологии, данные", icon: Code },
  { id: "medicine", name: "Медицина", description: "Здравоохранение, биология, фармация", icon: HeartPulse },
  { id: "pedagogy", name: "Педагогика", description: "Образование, развитие, воспитание", icon: GraduationCap },
  { id: "economics", name: "Экономика", description: "Финансы, менеджмент, бизнес", icon: TrendingUp },
  { id: "law", name: "Право", description: "Юриспруденция, правовое регулирование", icon: Scale },
  { id: "engineering", name: "Инженерия", description: "Промышленность, строительство, энергетика", icon: Cpu },
  { id: "art", name: "Искусство", description: "Дизайн, медиа, творческие профессии", icon: Palette },
  { id: "linguistics", name: "Лингвистика", description: "Языки, перевод, коммуникации", icon: Languages },
  { id: "agronomy", name: "Агрономия", description: "Сельское хозяйство, экология, природопользование", icon: Wheat },
  { id: "psychology", name: "Психология", description: "Психика, поведение, консультирование", icon: Brain },
  { id: "architecture", name: "Архитектура", description: "Проектирование зданий, урбанистика, дизайн среды", icon: Building2 },
  { id: "marketing", name: "Маркетинг", description: "Продвижение, бренд,Digital-стратегии", icon: Megaphone },
  { id: "construction", name: "Строительство", description: "ЖКХ, инфраструктура, управление проектами", icon: HardHat },
  { id: "energy", name: "Энергетика", description: "Электричество, нефть, газ, возобновляемые источники", icon: Zap },
  { id: "management", name: "Менеджмент", description: "Лидерство, процессы, управление командами", icon: Briefcase },
];
